const raw_material = [
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
     { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"}, { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"},
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    { name: "copper" },
    { name: "plastic" },
    {name:"smoke"},
    {name:"iron"},
    {name:"nickel"},
    {name:"titanium"},
    {name:"copper"}
]

export default raw_material;